remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag

title: Arkhive
description: "A “lifestyle” blog for facing down the data apocalypse"
show_downloads: "false"
show_header: "false"